version: '3'
volumes:
    data:
services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: svoris
            POSTRES_PASSWORD: svoris
        volumes:
            - data:/var/lib/postgresql/data
        ports:
            - "6432:5432"
