version: '1'
volumes:
    data:
services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: svoris
            POSTRES_PASSWORD: svoris
        volumes:
            - data:/var/lib/postgresql/data
        ports:
            - "6432:5432"
    frontend:
        image: node:5.10
        working_dir: /frontend
        command: npm run-script develop
        volumes:
            - ./frontend:/frontend
            - ./backend:/backend
        ports:
            - "3000:3000"
    django:
        build: ./backend
        volumes:
            - ./backend:/app
            - ./backend/media:/media
            - ./frontend/dist:/static
        command: ./bin/develop.sh
        ports:
            - "8000:8000"
        environment:
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_DEV}
            DB_NAME: django
            DB_USER: django
            DB_HOST: db
            DB_PORT: 5432
        depends_on:
            - db
