"""empty message

Revision ID: 36b3ebebda3c
Revises: a59d2a8261ed
Create Date: 2017-08-07 20:53:02.419111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b3ebebda3c'
down_revision = 'a59d2a8261ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pressures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('for_date', sa.DateTime(), nullable=True),
    sa.Column('for_hour', sa.Integer(), nullable=True),
    sa.Column('sys', sa.Integer(), nullable=True),
    sa.Column('dia', sa.Integer(), nullable=True),
    sa.Column('pul', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pressures')
    # ### end Alembic commands ###
